when:
  - branch: [main]
    event: push

steps:
  void-build-push:
    image: reg.hentioe.dev/library/plugin-docker-buildx
    privileged: true
    pull: true
    settings:
      repo: hentioe/rust
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: stable/void/Dockerfile
      context: stable/void
      platforms: linux/amd64,linux/arm64/v8
      tags:
        - latest
        - 1-void
        - 1.88-void
        - 1.88.0-void

  void-bindings-build-push:
    image: reg.hentioe.dev/library/plugin-docker-buildx
    privileged: true
    pull: true
    settings:
      repo: hentioe/rust
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: stable/void-bindings/Dockerfile
      context: stable/void-bindings
      platforms: linux/amd64,linux/arm64/v8
      tags:
        - 1-void-bindings
        - 1.88-void-bindings
        - 1.88.0-void-bindings
